# Generated by Django 2.2.7 on 2019-11-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191116_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='digest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
