# Generated by Django 2.2.7 on 2020-01-08 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200107_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
            ],
            options={
                'ordering': ['created_time'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.comment',),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Article'),
        ),
    ]
