# Generated by Django 2.2.7 on 2020-03-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200109_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='picture',
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='use_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='태그 이름'),
        ),
    ]
