# Generated by Django 2.2.7 on 2020-03-24 07:49

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_popular_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('data', django_mysql.models.JSONField(default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
